"""Independent AgentKit version domains."""

PACKAGE_VERSION = "0.2.0"
SUPPORTED_REPOSITORY_FORMATS = (1, 2)
LATEST_REPOSITORY_FORMAT = 2
RECOMMENDED_PRESET_VERSION = 1
TASK_STATE_SCHEMA_VERSION = 1
AGENTS_MANAGED_ARTIFACT_VERSION = 2

